#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Important: this is a "declarative" backup
# It only specifies what to backup, the actual backup is done by Yunohost

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_script_progression "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP THE SYSTEMD SERVICE FILE
#=================================================

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP LOGROTATE CONFIGURATION
#=================================================

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP LOG DIRECTORY
#=================================================

ynh_backup "/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Backup script completed for $app"
