#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost
if ynh_hide_warnings yunohost service status "$app" >/dev/null 2>&1; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove "$app"
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing systemd service..."

# Remove the dedicated systemd config
ynh_config_remove_systemd

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE NODEJS
#=================================================
ynh_script_progression "Removing Node.js..."

ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
