#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"
chmod 600 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# REINSTALL NODE.JS
#=================================================
ynh_script_progression "Reinstalling Node.js..."

ynh_nodejs_install

#=================================================
# REINSTALL NPM DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling app dependencies..."

pushd "$install_dir"
    ynh_exec_as_app env PATH="$path_with_nodejs" npm install --omit=dev
popd

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
systemctl daemon-reload

ynh_restore "/etc/logrotate.d/$app"
ynh_restore "/var/log/$app"

yunohost service add "$app" --description="Suivi Ruches - Beekeeping monitoring app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Apiculture App disponible" --log_path="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration of $app completed"
